"""Initial migration

Revision ID: 672f5bb53f04
Revises: 36820bb151f2
Create Date: 2026-01-30 18:48:25.253921

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '672f5bb53f04'
down_revision: Union[str, Sequence[str], None] = '36820bb151f2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('grass', sa.Column('test', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('grass', 'test')
    # ### end Alembic commands ###
