"""empty message

Revision ID: 764493fb1071
Revises: 20e0082da1d2
Create Date: 2026-02-19 15:15:57.585599

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '764493fb1071'
down_revision: Union[str, Sequence[str], None] = '20e0082da1d2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'generation')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('generation', sa.INTEGER(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
