"""Initial migration

Revision ID: bbb7adc37a4b
Revises: 672f5bb53f04
Create Date: 2026-01-30 18:48:48.858688

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'bbb7adc37a4b'
down_revision: Union[str, Sequence[str], None] = '672f5bb53f04'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('grass', 'test')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('grass', sa.Column('test', mysql.INTEGER(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
